---
title: "`r sprintf('GitHub Dashboard for %s on %s', Sys.getenv('GITHUB_USER'), Sys.Date())`"
output:
  flexdashboard::flex_dashboard:
    theme: yeti
    orientation: rows
    vertical_layout: scroll
---

> Derived from `hrbrmstr/githubdashboard`

```{r setup, echo=FALSE, include=FALSE}
library(flexdashboard)
library(gh)
library(anytime)
library(tidyverse)
library(DT)
library(knitr)
```

```{r fetch_data, echo=FALSE, include=FALSE}
USER <- Sys.getenv('GITHUB_USER')

user <- gh("/users/:user", user = USER)
repos <- gh("/users/:user/repos", user = USER, .limit = Inf)
issues <- gh("/user/issues", .limit = Inf)
starred <- gh("/user/starred", user = USER, .limit = Inf)
```

```{r extract_data_frames}
map_df(starred, ~{
  list(full_name = .x$full_name,
       name = .x$name,
       html_url = .x$html_url,
       description = .x$description %||% NA,
       open_issues = .x$open_issues %||% NA,
       stargazers_count = .x$stargazers_count,
       watchers_counts = .x$watchers_count %||% NA,
       forks_count = .x$forks_count %||% NA,
       has_issues = .x$has_issues %||% NA,
       updated_at = .x$updated_at %||% NA,
       pushed_at = .x$pushed_at %||% NA
  )
  }, .id = "starred_order") %>% 
  mutate(updated_at = anytime(updated_at, asUTC = TRUE), 
         pushed_at = NULL,
         description = stringi::stri_escape_unicode(description), 
         starred_order = as.numeric(starred_order)) ->
  starred_df

map_df(repos, ~{
  list(full_name = .x$full_name,
       name = .x$name,
       html_url = .x$html_url,
       description = .x$description %||% NA,
       open_issues = .x$open_issues %||% NA,
       stargazers_count = .x$stargazers_count,
       watchers_counts = .x$watchers_count %||% NA,
       forks_count = .x$forks_count %||% NA,
       has_issues = .x$has_issues %||% NA,
       updated_at = .x$updated_at %||% NA,
       pushed_at = .x$pushed_at %||% NA
  )
  }) %>% mutate(updated_at = anytime(updated_at, asUTC = TRUE), 
                description = stringi::stri_escape_unicode(description),
                pushed_at = NULL) -> repos_df

map_df(issues, function(x) {
  c(list(repo_name = x$repository$full_name,
         repo_url = x$repository$html_url,
         user_login = x$user$login,
         user_url = x$user$url),
    x[c("html_url", "number", "state", "updated_at", "created_at", "title", "body")])
}) %>%
  mutate(updated_at = anytime(created_at, asUTC = TRUE), created_at = NULL) -> issues_df
```

```{r include=FALSE}
options(
  DT.options =
    list(
      pageLength = 15,
      language = list(search = 'Filter:'),
      dom = 'Bfrtip',
      bInfo = FALSE)
)

pretty_diff <- function(rel) {
  map_chr(rel, function(x) {
    x <- Sys.time() - as.POSIXct(x, tz = Sys.timezone())
    y <- unclass(x)
    attr(y, "units") <- NULL
    # sprintf("%3.2f %s",  abs(y), attr(x, "units"))
    paste(format(abs(y), digits = 0, nsmall = 2), attr(x, "units"))
  })
}

starred_df %>%
  mutate(Repository = sprintf('<a href="%s">%s</a>', html_url, full_name)) %>%
  rename(Stars = stargazers_count, `Issues` = open_issues, 
         Order = starred_order, Description = description) %>%
  select(Repository, everything(), -name, -html_url) -> starred_df

repos_df %>%
  mutate(Repository = sprintf('<a href="%s">%s</a>', html_url, name)) %>%
  rename(Stars = stargazers_count, `Issues` = open_issues, Description = description) %>%
  select(Repository, everything(), -full_name, -name, -html_url, -has_issues) -> repos_df

issues_df %>%
  rename(Title = title) %>% 
  mutate(Repository = sprintf('<a href="%s">%s</a>', repo_url, repo_name),
         `Submitted by` = sprintf('<a href="%s">%s</a>', user_url, user_login),
         `Issue #` = sprintf('<a href="%s">#%s</a>', html_url, number),
         Age = pretty_diff(updated_at)) -> issues_df
```

Overview
=================================

Row
-----------------------------------------------------------------------

### Total Public Repos

```{r}
valueBox(scales::comma(nrow(repos_df)), icon = "fa-github")
```

### Open Issues

```{r open_issues}
valueBox(scales::comma(nrow(filter(issues_df, state == "open"))),
                       icon = "fa-exclamation-triangle")
```

### Total Stars Received

```{r}
valueBox(scales::comma(sum(repos_df$Stars)), icon = "fa-star")
```

Row
-----------------------------------------------------------------------

### Most recently starred repos

```{r recently_starred, include=TRUE}
arrange(starred_df, Order) %>% 
  filter(stringi::stri_startswith_fixed(full_name, "davidski") == FALSE) %>% 
  select(Order, Repository, -updated_at, Description, -watchers_counts) %>%
  datatable(options = list(paging = TRUE), escape = FALSE, rownames = FALSE)
```

Row
-----------------------------------------------------------------------

### My repos by time of last activity

```{r include=TRUE}
arrange(repos_df, desc(updated_at)) %>%
  select(Repository, Description, Age = updated_at, Stars, Issues) %>%
  mutate(Age = pretty_diff(Age)) %>% 
  datatable(options = list(bFilter = FALSE, paging = TRUE, 
                           columnDefs = list(list(className = 'dt-right', 
                                                  targets = c(2:4)))), 
            escape = FALSE, filter = "none", rownames = FALSE)
```

Row
-----------------------------------------------------------------------

### Open issues by date

```{r include=TRUE}
filter(issues_df, state == "open") %>%
  arrange(desc(updated_at)) %>%
  select(Repository, `Submitted by`, Title, `Issue #`, Age) %>%
  datatable(options = list(bFilter = FALSE, paging = FALSE, 
                           columnDefs = list(list(className = 'dt-right', 
                                                  targets = c(3:4)))), 
            escape = FALSE, filter = "none", rownames = FALSE)
```

